version: '3'

services:
  backend:
    build: .
    container_name: 'backend'
    volumes:
      - .:/app
    environment:
      - 'KAFKA_BROKER=kafka:9092'
    ports:
      - '3000:3000'
    command: ['node', '/app/dist/src/main.js']
    depends_on:
      - kafka
  kafka:
    image: 'bitnami/kafka:2.8.0'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    environment:
      - 'ALLOW_ANONYMOUS_LOGIN=yes'
